name: node_js_server_ci_pipelien

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: self-hosted

    env:
      PORT: ${{ vars.PORT }}

    steps:

      - name: Stop old server
        run: |
          PID=$(lsof -t -i:$PORT || true)
          if [ -n "$PID" ]; then
            kill $PID
          fi

      - name: first step to clone repo in local system
        uses: actions/checkout@v4

      - name: setup node 24 for deployment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install node dependecies
        run: npm ci

      - name: deployment phase
        run: |
          nohup node server.js > server.log 2>&1 < /dev/null &
          sleep 2
          cat server.log
